"use strict";
// @generated by protoc-gen-connect-es v0.12.0 with parameter "target=ts"
// @generated from file logins.proto (package scanswift, syntax proto3)
/* eslint-disable */
// @ts-nocheck
Object.defineProperty(exports, "__esModule", { value: true });
exports.LoginService = void 0;
const logins_pb_js_1 = require("./logins_pb.js");
const protobuf_1 = require("@bufbuild/protobuf");
const base_pb_js_1 = require("./base_pb.js");
/**
 *
 * Describes the methods applicable on the login service
 *
 * @generated from service scanswift.LoginService
 */
exports.LoginService = {
    typeName: "scanswift.LoginService",
    methods: {
        /**
         * Login using credentials belonging to a user
         *
         * @generated from rpc scanswift.LoginService.UserLogin
         */
        userLogin: {
            name: "UserLogin",
            I: logins_pb_js_1.UserLoginRequest,
            O: logins_pb_js_1.UserLoginResponse,
            kind: protobuf_1.MethodKind.Unary,
        },
        /**
         * Check if the auth token is still valid
         *
         * @generated from rpc scanswift.LoginService.IsAuthTokenValid
         */
        isAuthTokenValid: {
            name: "IsAuthTokenValid",
            I: logins_pb_js_1.AuthTokenValidityRequest,
            O: base_pb_js_1.BooleanResponse,
            kind: protobuf_1.MethodKind.Unary,
        },
        /**
         * Logout
         *
         * @generated from rpc scanswift.LoginService.Logout
         */
        logout: {
            name: "Logout",
            I: logins_pb_js_1.LogoutRequest,
            O: logins_pb_js_1.LogoutResponse,
            kind: protobuf_1.MethodKind.Unary,
        },
    }
};
