// @generated by protoc-gen-connect-es v0.12.0 with parameter "target=ts"
// @generated from file batches.proto (package scanswift, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { Batch, BatchesList, BatchesServiceCommissioningRequest, BatchesServiceCreateRequest, BatchesServiceFilterReq, BatchesServicePaginationReq, BatchesServiceSearchAllReq, BatchIdentifierWithSerialState, BatchPaginationResp } from "./batches_pb.js";
import { MethodKind } from "@bufbuild/protobuf";
import { ActiveInEntityRequest, CountInEntityRequest, CountResponse, FileResponse, FileResponseList, Identifier, IdentifierWithUserComment, SearchKeyRequest } from "./base_pb.js";

/**
 *
 * Describes the methods applicable on each batch
 *
 * @generated from service scanswift.BatchesService
 */
export const BatchesService = {
  typeName: "scanswift.BatchesService",
  methods: {
    /**
     * Create a batch
     *
     * // Update a batch
     * rpc Update (BatchesServiceUpdateRequest) returns (Batch);
     *
     * @generated from rpc scanswift.BatchesService.Create
     */
    create: {
      name: "Create",
      I: BatchesServiceCreateRequest,
      O: Batch,
      kind: MethodKind.Unary,
    },
    /**
     * Archive the batch
     *
     * @generated from rpc scanswift.BatchesService.Archive
     */
    archive: {
      name: "Archive",
      I: IdentifierWithUserComment,
      O: Identifier,
      kind: MethodKind.Unary,
    },
    /**
     * Restore the batch
     *
     * @generated from rpc scanswift.BatchesService.Restore
     */
    restore: {
      name: "Restore",
      I: IdentifierWithUserComment,
      O: Identifier,
      kind: MethodKind.Unary,
    },
    /**
     * Recall the batch
     *
     * @generated from rpc scanswift.BatchesService.Recall
     */
    recall: {
      name: "Recall",
      I: IdentifierWithUserComment,
      O: Identifier,
      kind: MethodKind.Unary,
    },
    /**
     * Commission unused serials
     *
     * @generated from rpc scanswift.BatchesService.CommissionUnused
     */
    commissionUnused: {
      name: "CommissionUnused",
      I: BatchesServiceCommissioningRequest,
      O: Identifier,
      kind: MethodKind.Unary,
    },
    /**
     * Decommission unused serials
     *
     * @generated from rpc scanswift.BatchesService.DecommissionUnused
     */
    decommissionUnused: {
      name: "DecommissionUnused",
      I: BatchesServiceCommissioningRequest,
      O: Identifier,
      kind: MethodKind.Unary,
    },
    /**
     * View by UUID
     *
     * @generated from rpc scanswift.BatchesService.ViewByUUID
     */
    viewByUUID: {
      name: "ViewByUUID",
      I: Identifier,
      O: Batch,
      kind: MethodKind.Unary,
    },
    /**
     * View by Code
     *
     * @generated from rpc scanswift.BatchesService.ViewByCode
     */
    viewByCode: {
      name: "ViewByCode",
      I: SearchKeyRequest,
      O: Batch,
      kind: MethodKind.Unary,
    },
    /**
     * View all batches
     *
     * @generated from rpc scanswift.BatchesService.ViewAll
     */
    viewAll: {
      name: "ViewAll",
      I: ActiveInEntityRequest,
      O: BatchesList,
      kind: MethodKind.Unary,
    },
    /**
     * View batches with pagination
     *
     * @generated from rpc scanswift.BatchesService.ViewWithPagination
     */
    viewWithPagination: {
      name: "ViewWithPagination",
      I: BatchesServicePaginationReq,
      O: BatchPaginationResp,
      kind: MethodKind.Unary,
    },
    /**
     * Download all the serials (in the given state) within the batch as a PDF
     *
     * @generated from rpc scanswift.BatchesService.DownloadSerialsAsPDF
     */
    downloadSerialsAsPDF: {
      name: "DownloadSerialsAsPDF",
      I: BatchIdentifierWithSerialState,
      O: FileResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Download all the serials (in the given state) within the batch as a CSV file
     *
     * @generated from rpc scanswift.BatchesService.DownloadSerialsAsCSV
     */
    downloadSerialsAsCSV: {
      name: "DownloadSerialsAsCSV",
      I: BatchIdentifierWithSerialState,
      O: FileResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Download all the serials (in the given state) within the batch as a single image
     *
     * @generated from rpc scanswift.BatchesService.DownloadSerialsAsImage
     */
    downloadSerialsAsImage: {
      name: "DownloadSerialsAsImage",
      I: BatchIdentifierWithSerialState,
      O: FileResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Download all the serials (in the given state) within the batch as multiple images
     *
     * @generated from rpc scanswift.BatchesService.DownloadSerialsAsImagesWithDescriptions
     */
    downloadSerialsAsImagesWithDescriptions: {
      name: "DownloadSerialsAsImagesWithDescriptions",
      I: BatchIdentifierWithSerialState,
      O: FileResponseList,
      kind: MethodKind.Unary,
    },
    /**
     * View all that match the given search key
     *
     * @generated from rpc scanswift.BatchesService.SearchAll
     */
    searchAll: {
      name: "SearchAll",
      I: BatchesServiceSearchAllReq,
      O: BatchesList,
      kind: MethodKind.Unary,
    },
    /**
     * View all that match the given filter criteria
     *
     * @generated from rpc scanswift.BatchesService.Filter
     */
    filter: {
      name: "Filter",
      I: BatchesServiceFilterReq,
      O: BatchesList,
      kind: MethodKind.Unary,
    },
    /**
     * Count
     *
     * @generated from rpc scanswift.BatchesService.Count
     */
    count: {
      name: "Count",
      I: CountInEntityRequest,
      O: CountResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

