// @generated by protoc-gen-connect-es v0.12.0 with parameter "target=ts"
// @generated from file printers.proto (package tcube, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { Printer, PrinterPaginationResp, PrintersList, PrintersServiceCreateRequest, PrintersServiceFilterReq, PrintersServicePaginationReq, PrintersServiceSearchAllReq, PrintersServiceUpdateRequest } from "./printers_pb.js";
import { MethodKind } from "@bufbuild/protobuf";
import { ActiveInEntityRequest, CountInLocationRequest, CountResponse, Identifier, IdentifierWithUserComment } from "./base_pb.js";

/**
 *
 * Describes the methods applicable on each printer
 *
 * @generated from service tcube.PrintersService
 */
export const PrintersService = {
  typeName: "tcube.PrintersService",
  methods: {
    /**
     * Create a printer
     *
     * @generated from rpc tcube.PrintersService.Create
     */
    create: {
      name: "Create",
      I: PrintersServiceCreateRequest,
      O: Printer,
      kind: MethodKind.Unary,
    },
    /**
     * Update a printer
     *
     * @generated from rpc tcube.PrintersService.Update
     */
    update: {
      name: "Update",
      I: PrintersServiceUpdateRequest,
      O: Printer,
      kind: MethodKind.Unary,
    },
    /**
     * Archive the printer
     *
     * @generated from rpc tcube.PrintersService.Archive
     */
    archive: {
      name: "Archive",
      I: IdentifierWithUserComment,
      O: Identifier,
      kind: MethodKind.Unary,
    },
    /**
     * Restore the printer
     *
     * @generated from rpc tcube.PrintersService.Restore
     */
    restore: {
      name: "Restore",
      I: IdentifierWithUserComment,
      O: Identifier,
      kind: MethodKind.Unary,
    },
    /**
     * View by UUID
     *
     * @generated from rpc tcube.PrintersService.ViewByUUID
     */
    viewByUUID: {
      name: "ViewByUUID",
      I: Identifier,
      O: Printer,
      kind: MethodKind.Unary,
    },
    /**
     * View all printers
     *
     * @generated from rpc tcube.PrintersService.ViewAll
     */
    viewAll: {
      name: "ViewAll",
      I: ActiveInEntityRequest,
      O: PrintersList,
      kind: MethodKind.Unary,
    },
    /**
     * View printers with pagination
     *
     * @generated from rpc tcube.PrintersService.ViewWithPagination
     */
    viewWithPagination: {
      name: "ViewWithPagination",
      I: PrintersServicePaginationReq,
      O: PrinterPaginationResp,
      kind: MethodKind.Unary,
    },
    /**
     * View all that match the given search key
     *
     * @generated from rpc tcube.PrintersService.SearchAll
     */
    searchAll: {
      name: "SearchAll",
      I: PrintersServiceSearchAllReq,
      O: PrintersList,
      kind: MethodKind.Unary,
    },
    /**
     * View all that match the given filter criteria
     *
     * @generated from rpc tcube.PrintersService.Filter
     */
    filter: {
      name: "Filter",
      I: PrintersServiceFilterReq,
      O: PrintersList,
      kind: MethodKind.Unary,
    },
    /**
     * Count
     *
     * @generated from rpc tcube.PrintersService.Count
     */
    count: {
      name: "Count",
      I: CountInLocationRequest,
      O: CountResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

