// @generated by protoc-gen-connect-es v0.12.0 with parameter "target=ts"
// @generated from file roles.proto (package scanswift, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { Role, RolePaginationResp, RolesList, RolesServiceCreateRequest, RolesServicePaginationReq, RolesServiceUpdateRequest } from "./roles_pb.js";
import { MethodKind } from "@bufbuild/protobuf";
import { ActiveRequest, Identifier, IdentifierWithUserComment } from "./base_pb.js";

/**
 *
 * Describes the methods applicable on each role
 *
 * @generated from service scanswift.RolesService
 */
export const RolesService = {
  typeName: "scanswift.RolesService",
  methods: {
    /**
     * Create a role
     *
     * @generated from rpc scanswift.RolesService.Create
     */
    create: {
      name: "Create",
      I: RolesServiceCreateRequest,
      O: Role,
      kind: MethodKind.Unary,
    },
    /**
     * Update a role
     *
     * @generated from rpc scanswift.RolesService.Update
     */
    update: {
      name: "Update",
      I: RolesServiceUpdateRequest,
      O: Role,
      kind: MethodKind.Unary,
    },
    /**
     * Archive the role
     *
     * @generated from rpc scanswift.RolesService.Archive
     */
    archive: {
      name: "Archive",
      I: IdentifierWithUserComment,
      O: Identifier,
      kind: MethodKind.Unary,
    },
    /**
     * Restore the role
     *
     * @generated from rpc scanswift.RolesService.Restore
     */
    restore: {
      name: "Restore",
      I: IdentifierWithUserComment,
      O: Identifier,
      kind: MethodKind.Unary,
    },
    /**
     * View by UUID
     *
     * @generated from rpc scanswift.RolesService.ViewByUUID
     */
    viewByUUID: {
      name: "ViewByUUID",
      I: Identifier,
      O: Role,
      kind: MethodKind.Unary,
    },
    /**
     * View all roles
     *
     * @generated from rpc scanswift.RolesService.ViewAll
     */
    viewAll: {
      name: "ViewAll",
      I: ActiveRequest,
      O: RolesList,
      kind: MethodKind.Unary,
    },
    /**
     * View roles with pagination
     *
     * @generated from rpc scanswift.RolesService.ViewWithPagination
     */
    viewWithPagination: {
      name: "ViewWithPagination",
      I: RolesServicePaginationReq,
      O: RolePaginationResp,
      kind: MethodKind.Unary,
    },
  }
} as const;

