// @generated by protoc-gen-connect-es v0.12.0 with parameter "target=ts"
// @generated from file serials_reviews.proto (package tcube, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { SerialReview, SerialReviewPaginationResp, SerialsReviewsList, SerialsReviewsServiceCreateRequest, SerialsReviewsServiceFilterReq, SerialsReviewsServicePaginationReq, SerialsReviewsServiceSearchAllReq, SerialsReviewsServiceUpdateRequest } from "./serials_reviews_pb.js";
import { MethodKind } from "@bufbuild/protobuf";
import { ActiveForProductRequest, CountForProductRequest, CountResponse, Identifier, IdentifierWithUserComment } from "./base_pb.js";

/**
 *
 * Describes the methods applicable on each serial review
 *
 * @generated from service tcube.SerialsReviewsService
 */
export const SerialsReviewsService = {
  typeName: "tcube.SerialsReviewsService",
  methods: {
    /**
     * Create a serial review
     *
     * @generated from rpc tcube.SerialsReviewsService.Create
     */
    create: {
      name: "Create",
      I: SerialsReviewsServiceCreateRequest,
      O: SerialReview,
      kind: MethodKind.Unary,
    },
    /**
     * Update a serial review
     *
     * @generated from rpc tcube.SerialsReviewsService.Update
     */
    update: {
      name: "Update",
      I: SerialsReviewsServiceUpdateRequest,
      O: SerialReview,
      kind: MethodKind.Unary,
    },
    /**
     * Archive the serial review
     *
     * @generated from rpc tcube.SerialsReviewsService.Archive
     */
    archive: {
      name: "Archive",
      I: IdentifierWithUserComment,
      O: Identifier,
      kind: MethodKind.Unary,
    },
    /**
     * Restore the serial review
     *
     * @generated from rpc tcube.SerialsReviewsService.Restore
     */
    restore: {
      name: "Restore",
      I: IdentifierWithUserComment,
      O: Identifier,
      kind: MethodKind.Unary,
    },
    /**
     * View by UUID
     *
     * @generated from rpc tcube.SerialsReviewsService.ViewByUUID
     */
    viewByUUID: {
      name: "ViewByUUID",
      I: Identifier,
      O: SerialReview,
      kind: MethodKind.Unary,
    },
    /**
     * View all serials reviews
     *
     * @generated from rpc tcube.SerialsReviewsService.ViewAll
     */
    viewAll: {
      name: "ViewAll",
      I: ActiveForProductRequest,
      O: SerialsReviewsList,
      kind: MethodKind.Unary,
    },
    /**
     * View serials reviews with pagination
     *
     * @generated from rpc tcube.SerialsReviewsService.ViewWithPagination
     */
    viewWithPagination: {
      name: "ViewWithPagination",
      I: SerialsReviewsServicePaginationReq,
      O: SerialReviewPaginationResp,
      kind: MethodKind.Unary,
    },
    /**
     * View all that match the given search key
     *
     * @generated from rpc tcube.SerialsReviewsService.SearchAll
     */
    searchAll: {
      name: "SearchAll",
      I: SerialsReviewsServiceSearchAllReq,
      O: SerialsReviewsList,
      kind: MethodKind.Unary,
    },
    /**
     * View all that match the given filter criteria
     *
     * @generated from rpc tcube.SerialsReviewsService.Filter
     */
    filter: {
      name: "Filter",
      I: SerialsReviewsServiceFilterReq,
      O: SerialsReviewsList,
      kind: MethodKind.Unary,
    },
    /**
     * Count
     *
     * @generated from rpc tcube.SerialsReviewsService.Count
     */
    count: {
      name: "Count",
      I: CountForProductRequest,
      O: CountResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

