// @generated by protoc-gen-connect-es v0.12.0 with parameter "target=ts"
// @generated from file zones.proto (package scanswift, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { Zone, ZonePaginationResp, ZonesList, ZonesServiceCreateRequest, ZonesServiceFilterReq, ZonesServicePaginationReq, ZonesServiceSearchAllReq, ZonesServiceUpdateRequest } from "./zones_pb.js";
import { MethodKind } from "@bufbuild/protobuf";
import { ActiveInEntityRequest, CountInEntityRequest, CountResponse, Identifier, IdentifierWithUserComment, ImageAssignRequest, ImageResponse } from "./base_pb.js";

/**
 *
 * Describes the methods applicable on each zone
 *
 * @generated from service scanswift.ZonesService
 */
export const ZonesService = {
  typeName: "scanswift.ZonesService",
  methods: {
    /**
     * Create a zone
     *
     * @generated from rpc scanswift.ZonesService.Create
     */
    create: {
      name: "Create",
      I: ZonesServiceCreateRequest,
      O: Zone,
      kind: MethodKind.Unary,
    },
    /**
     * Update a zone
     *
     * @generated from rpc scanswift.ZonesService.Update
     */
    update: {
      name: "Update",
      I: ZonesServiceUpdateRequest,
      O: Zone,
      kind: MethodKind.Unary,
    },
    /**
     * Archive the zone
     *
     * @generated from rpc scanswift.ZonesService.Archive
     */
    archive: {
      name: "Archive",
      I: IdentifierWithUserComment,
      O: Identifier,
      kind: MethodKind.Unary,
    },
    /**
     * Restore the zone
     *
     * @generated from rpc scanswift.ZonesService.Restore
     */
    restore: {
      name: "Restore",
      I: IdentifierWithUserComment,
      O: Identifier,
      kind: MethodKind.Unary,
    },
    /**
     * Assign image
     *
     * @generated from rpc scanswift.ZonesService.AssignImage
     */
    assignImage: {
      name: "AssignImage",
      I: ImageAssignRequest,
      O: Identifier,
      kind: MethodKind.Unary,
    },
    /**
     * View assigned image
     *
     * @generated from rpc scanswift.ZonesService.ViewImage
     */
    viewImage: {
      name: "ViewImage",
      I: Identifier,
      O: ImageResponse,
      kind: MethodKind.Unary,
    },
    /**
     * View by UUID
     *
     * @generated from rpc scanswift.ZonesService.ViewByUUID
     */
    viewByUUID: {
      name: "ViewByUUID",
      I: Identifier,
      O: Zone,
      kind: MethodKind.Unary,
    },
    /**
     * View all zones
     *
     * @generated from rpc scanswift.ZonesService.ViewAll
     */
    viewAll: {
      name: "ViewAll",
      I: ActiveInEntityRequest,
      O: ZonesList,
      kind: MethodKind.Unary,
    },
    /**
     * View zones with pagination
     *
     * @generated from rpc scanswift.ZonesService.ViewWithPagination
     */
    viewWithPagination: {
      name: "ViewWithPagination",
      I: ZonesServicePaginationReq,
      O: ZonePaginationResp,
      kind: MethodKind.Unary,
    },
    /**
     * View all that match the given search key
     *
     * @generated from rpc scanswift.ZonesService.SearchAll
     */
    searchAll: {
      name: "SearchAll",
      I: ZonesServiceSearchAllReq,
      O: ZonesList,
      kind: MethodKind.Unary,
    },
    /**
     * View all that match the given filter criteria
     *
     * @generated from rpc scanswift.ZonesService.Filter
     */
    filter: {
      name: "Filter",
      I: ZonesServiceFilterReq,
      O: ZonesList,
      kind: MethodKind.Unary,
    },
    /**
     * Count
     *
     * @generated from rpc scanswift.ZonesService.Count
     */
    count: {
      name: "Count",
      I: CountInEntityRequest,
      O: CountResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

